services:
      cha-de-panela:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: cha_cozinha_miguel_ana
        restart: unless-stopped
        ports:
          - "3030:4000"
        environment:
          - NODE_ENV=production
          - PORT=4000
        volumes:
          - ./data:/app/server/data
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.chapanela.rule=Host(`convite.miguel-ana.infotechti.tech`)"
          - "traefik.http.routers.chapanela.entrypoints=websecure"
          - "traefik.http.routers.chapanela.tls.certresolver=letsencrypt"
          - "traefik.http.services.chapanela.loadbalancer.server.port=4000"
